Repository younsl/idled, pull requests merged in 2025-04, with the labels that each got.

#9 feat: Add IAM idle resource detection feature
  README.md
  cmd/idled/main.go
  docs/project-structure.md
  go.mod
  go.sum
  internal/models/iam.go
  pkg/aws/iam.go
  pkg/formatter/iam_table.go
Labels: enhancement, cloud-provider/aws, feature

#13 release: idled 0.4.0
  README.md
  cmd/idled/main.go
  docs/project-structure.md
  go.mod
  go.sum
  internal/models/config.go
  internal/models/iam.go
  pkg/aws/config.go
  pkg/aws/iam.go
  pkg/formatter/config_table.go
  pkg/formatter/iam_table.go
Labels: release

#14 feat: Support scanning idle ELB (ALB/NLB)
  README.md
  cmd/idled/main.go
  docs/aws/config.md
  docs/aws/ebs.md
  docs/aws/ec2.md
  docs/aws/eip.md
  docs/aws/elb.md
  docs/aws/iam.md
  docs/aws/lambda.md
  docs/aws/s3.md
  docs/cost-savings-calculation.md
  docs/project-structure.md
  go.mod
  go.sum
  internal/models/elb.go
  pkg/aws/elb.go
  pkg/formatter/elb_table.go
Labels: enhancement, cloud-provider/aws, feature

#37 release: idled 0.8.0
  README.md
  cmd/idled/main.go
  docs/available-services.md
  docs/aws/msk.md
  go.mod
  go.sum
  internal/models/msk.go
  pkg/aws/msk.go
  pkg/formatter/msk_table.go
Labels: release

#38 feat: Add AWS Secrets Manager scanner
  README.md
  cmd/idled/main.go
  docs/available-services.md
  docs/aws/secretsmanager.md
  go.mod
  go.sum
  internal/models/secretsmanager.go
  pkg/aws/secretsmanager.go
  pkg/formatter/secretsmanager_table.go
Labels: feature

#39 release: idled 0.9.0
  README.md
  cmd/idled/main.go
  docs/available-services.md
  docs/aws/secretsmanager.md
  go.mod
  go.sum
  internal/models/secretsmanager.go
  pkg/aws/secretsmanager.go
  pkg/formatter/secretsmanager_table.go
Labels: release
